# basic options
title: devlog
author: Kao Tica
email: k40t1c4[AT]gmail.com
description: test of hacker theme
twitter_username: tbd
github_username:  KaoTica

# Build settings
markdown: kramdown
theme: minima
